- name: gp
  configMap:
    name: gpmplanerouterpolicy
- name: data
  persistentVolumeClaim:
    claimName: data
- name: mdt
  persistentVolumeClaim:
    claimName: mdt
- name: dumps
  persistentVolumeClaim:
    claimName: hcdumps
- name: smrs
  persistentVolumeClaim:
     claimName: smrs
